# 2_7_플로우_예외처리하기

### 수집기 측에서 예외처리하기
- `collect`를 하는 수집기 측에서 try-catch 식을 이용해 예외처리한다.

```kotlin
fun simple(): Flow<Int> = flow {
    for (i in 1..3) {
        println("Emitting $i")
        emit(i)
    }
}

fun main() = runBlocking {
    try {
        simple().collect { value ->
            println(value)
            check(value <= 1) { "Collected $value" }
        }
    } catch (e: Throwable) {
        println("Caught $e")
    }
}
```

### 모든 예외는 처리 가능
- 어느 곳에서 발생한 예외라도 처리가 가능하다.

```kotlin
fun simple(): Flow<String> =
    flow {
        for (i in 1..3) {
            println("Emitting $i")
            emit(i)
        }
    }.map { value ->
        check(value <= 1) { "Crashed on $value" }
        "string $value"
    }

fun main() = runBlocking {
    try {
        simple().collect { value -> println(value) }
    } catch (e: Throwable) {
        println("Caught $e")
    }
}
```

### 예외 투명성
- 빌더 코드 블록 내에서 예외를 처리하는 것은 예외 투명성을 어기는 것이다.
- `flow` 내부에서 예외를 처리하면 외부에서 알 수 없기 때문이다.
- 플로우에서 `catch` 연산자를 이용하는 것이 권장된다.
- `catch` 블록에서 예외를 새로운 데이터로 만들어 `emit` 하거나, 다시 예외를 던지거나, 로그를 남길 수 있다.

```kotlin
fun simple(): Flow<Int> = flow {
    for (i in 1..3) {
        println("Emitting $i")
        emit(i)
        }
    }
    .map { value ->
        check(value <= 1) { "Crashed on $value" }
        "string $value"
    }

fun main() = runBlocking {
    simple1()
        .catch { e -> emit("Caught $e") }
        .collect { value -> println(value) }
}
```

### catch 투명성
- `catch` 연산자는 업스트림에만 영향을 미치고 다운스트림에는 영향을 미치지 않는다.
- 이를 catch 투명성이라 한다.

```kotlin
fun simple(): Flow<Int> = flow {
    for (i in 1..3)
        println("Emitting $i")
        emit(i)
    }
}

fun main() = runBlocking {
    simple1()
        .catch { e -> emit("Caught $e") }
        .collect { value -> 
            check(value <= 1) { "Collected $value" }
            println(value) 
        }
}
```