# 1_4_서스펜딩 함수

### suspend 함수들의 순차적인 수행
- 일반적인 함수 수행 과정처럼 `suspend` 함수들이 순차적으로 수행된다.
- 순차적으로 수행되는 이유는 한 번에 한 `suspend` 함수만 호출되기 때문이다.

```kotlin
suspend fun getRandom1(): Int {
    delay(1000L)
    return Random.nextInt(0, 500)
}

suspend fun getRandom2(): Int {
    delay(1000L)
    return Random.nextInt(0, 500)
}

fun main() = runBlocking {
    val elapsedTime = measureTimeMillis {
        val value1 = getRandom1()
        val value2 = getRandom2()
        println("${value1} + ${value2} = ${value1 + value2}")
    }
    println(elapsedTime)
}
```

### async를 이용해 동시 수행하기
- `async` 키워드는 동시에 다른 블록을 수행할 수 있으며, 수행 결과를 `await` 키워드를 통해 받을 수 있다.
- 결과를 받아야 한다면 `async`, 받지 않아도 된다면 `launch`를 선택할 수 있다 .
- `await()`는 `job.join()` + 결과를 가져오는 것으로 볼 수 있다.

```kotlin
suspend fun getRandom1(): Int {
    delay(1000L)
    return Random.nextInt(0, 500)
}

suspend fun getRandom2(): Int {
    delay(1000L)
    return Random.nextInt(0, 500)
}

fun main() = runBlocking {
    val elapsedTime = measureTimeMillis {
        val value1 = async { // this: 코루틴
            getRandom1()
        }
        val value2 = async { 
            getRandom2()
        }
        println("${value1.await()} + ${value2.await()} = ${value1.await() + value2.await()}") // suspension point
    }
    println(elapsedTime)
}
```

### async 게으르게 사용하기
- `async(start = CoroutineStart.LAZY` 로 인자를 전달하면 원하는 순간에 수행을 준비하게 할 수 있다.
- 이후 `start` 메서드를 이용해 큐에 수행 예약을 해서 수행을 준비하게 할 수 있다.

```kotlin
suspend fun getRandom1(): Int {
    delay(1000L)
    return Random.nextInt(0, 500)
}

suspend fun getRandom2(): Int {
    delay(1000L)
    return Random.nextInt(0, 500)
}

fun main() = runBlocking {
    val elapsedTime = measureTimeMillis {
        val value1 = async(start = CoroutineStart.LAZY) { getRandom1() }
        val value2 = async(start = CoroutineStart.LAZY) { getRandom2() }

        value1.start() 
        value2.start()

        println("${value1.await()} + ${value2.await()} = ${value1.await() + value2.await()}")
    }
    println(elapsedTime)
}
```

### async를 사용한 구조적인 동시성
- `getRandom2()`에서 에러가 발생하면 `getRandom1()`과 부모까지 전파되어 캔슬된다.

```kotlin
suspend fun getRandom1(): Int {
    try {
        delay(1000L)
        return Random.nextInt(0, 500)
    } finally {
        println("getRandom7 is cancelled.")
    }
}

suspend fun getRandom2(): Int {
    delay(500L)
    throw IllegalStateException()
}

suspend fun doSomething() = coroutineScope {
    val value1 = async {
        getRandom1()
    }
    val value2 = async {
        getRandom2()
    }
    try {
        println("${value1.await()} + ${value2.await()} = ${value1.await() + value2.await()}")
    } finally {
        println("doSomething is cancelled.")
    }
}

fun main() = runBlocking {
    try {
        doSomething()
    } catch (e: IllegalStateException) {
        println("doSomething failed: $e")
    }
}
```